spring.application.name: simplify-payment-transfer-api

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/simplify?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


spring.kafka:
  bootstrap-servers: ${KAFKA_URL:localhost:9094}
  producer:
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumer:
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties.spring.json.trusted.packages: '*'
